Repository iiits/alumni-portal, pull requests merged in 2025-01, with the labels that each got.

#1 Layout navbar
  app/globals.css
  app/layout.tsx
  app/page.tsx
  components.json
  components/Navbar.tsx
  components/icons.tsx
  components/ui/button.tsx
  components/ui/navigation-menu.tsx
  components/ui/sheet.tsx
  data/navbarItems.ts
  lib/utils.ts
  package-lock.json
  package.json
  tailwind.config.ts
Labels: enhancement

#9 Testimonials
  app/page.tsx
  components/LandingPage/AnimatedTestimonials.tsx
  data/testimonials.ts
  next.config.ts
  package-lock.json
  package.json
Labels: enhancement

#13 Fix across multiple pages
  app/page.tsx
  app/signup/page.tsx
  components/Navbar.tsx
  components/SignUpPage/Signup.tsx
  components/ui/animated-testimonials.tsx
  components/ui/label.tsx
  components/ui/navigation-menu.tsx
  data/navbarItems.ts
  package-lock.json
Labels: enhancement, bugfix

#15 Footer
  app/layout.tsx
  components/Footer.tsx
  components/Navbar.tsx
  data/footerItems.ts
  public/collegeLogo.png
Labels: enhancement

#16 Fixes
  components/Footer.tsx
  components/LandingPage/WorldMap.tsx
  components/Navbar.tsx
  components/SignUpPage/Signup.tsx
  components/ui/animated-testimonials.tsx
  components/ui/world-map.tsx
  data/footerItems.ts
  data/navbarItems.ts
  eslint.config.mjs
Labels: enhancement, bugfix

#17 Automation
  .github/workflows/notify-forks.yml
Labels: enhancement

#18 Build error fix
  components/ui/infinite-moving-cards.tsx
Labels: bugfix

#20 [BugFix] Build error fix
  components/LandingPage/Companies.tsx
Labels: enhancement

#22 404 Page & Favicon
  app/favicon.ico
  app/icon.ico
  app/not-found.tsx
  components/LandingPage/Companies.tsx
  components/LandingPage/HeroSec.tsx
  public/404.svg
  public/favicon.ico
Labels: enhancement
